version: '3.9'
services:
  postgres:
    image: ${PG_APP}
    container_name: ${PG_HOST}
    environment:
      - POSTGRES_DB=${PG_DB}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASS}
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      #- db-volume:/var/lib/postgresql/data
      - ./postgres_data:/var/lib/postgresql/data
volumes:
  db-volume:
    name: pg-data
